bernardopires/django-tenant-schemas

tenant_schemas/routers.py
From the Django 1.7 release notes:
> The allow_syncdb method on database routers is now called allow_migrate, but still performs the same function. Routers with allow_syncdb methods will still work, but that method name is deprecated and you should change it as soon as possible (nothing more than renaming is required).
=> Add database router allow_migrate() for Django 1.7

docs/install.rst, tenant_schemas/middleware.py, tenant_schemas/template_loaders.py
Treat an unknown tenant as though it were a request for a hostname not specified in `ALLOWED_HOSTS`.
=> Raise DisallowedHost instead of Http404

docs/use.rst, tenant_schemas/management/commands/list_tenants.py
It is useful to be able to export a list of `schema_name` to `domain_url` values for use in shell scripts.
=> Add list_tenants management command

tenant_schemas/management/commands/__init__.py, tenant_schemas/management/commands/migrate_schemas.py
Refactored code to meet new requirements of writing custom commands. https://docs.djangoproject.com/en/1.8/releases/1.8/#management-commands-that-only-accept-positional-arguments
=> make migrate_schemas work for django 1.8

tenant_schemas/routers.py
Django 1.8 will call it for RunPython and RunSQL operations, but we needed to update the method signature to opt-in. (those operations have no model)
See: https://docs.djangoproject.com/en/1.8/releases/1.8/#deprecated-signature-of-allow-migrate
I believe I've made it backwards compatible with 1.7 with lines 16-18, but since 1.7 will not check with `allow_migrate()` before running RunPython and RunSQL, 1.7 users will still need to employ the workaround in Issue #231.
=> Update allow_migrate() for Django 1.8. Fixes #231 (in 1.8)

docs/install.rst
The order of apps in `INSTALLED_APPS` can be significant in various cases. (per https://docs.djangoproject.com/en/1.8/ref/applications/
At each stage, Django processes all applications in the order of INSTALLED_APPS.)
The documented way to set `INSTALLED_APPS` will reset the order. This PR updates documentation to suggest how to maintain order in `INSTALLED_APPS`.
=> maintain order of installed_apps

tenant_schemas/urlresolvers.py
`reverse` no longer accepts the `prefix` argument
https://docs.djangoproject.com/en/1.9/ref/urlresolvers/#reverse
=> fix `reverse` for Django 1.9

docs/involved.rst, docs/test.rst, dts_test_project/dts_test_project/settings.py, tenant_schemas/tests/test_tenants.py, tenant_schemas/tests/testcases.py, tenant_schemas/utils.py, tox.ini
I had difficulty in running the test suite for myself, so I decided to bootstrap it with tox to simplify it for contributors.
Additionally I updated the test settings.py to read the postgres username and password from the environment variables `PG_USER` and `PG_PASSWORD` respectively, as documented at https://codeship.com/documentation/databases/postgresql/#django, to demonstrate how we could use a CI pipeline.
To make the tests work with Django 1.8 and 1.9 I needed to add a conditional check to `TenantCommandTest.test_command ` and also tweaked the verbosity calculation in the `BaseTestCase` so you get output that doesn't spam the terminal unless you trigger it with `-v 2`.
=> Use tox to execute the test suite

tenant_schemas/tests/test_utils.py, tenant_schemas/utils.py
Basically makes Django 1.7+ retrieve `app_label` from the `AppConfig` instead of string parsing.
Fixes https://github.com/bernardopires/django-tenant-schemas/issues/304
=> Added AppConfig handling to tenant_schemas.utils.app_labels

tenant_schemas/models.py
This avoids masking any errors that might happen in signal handlers.
This is related to #335
=> Only send post_sync_signal on successful schema creation

dts_test_project/dts_test_app/migrations/0002_test_drop_unique.py, tenant_schemas/postgresql_backend/introspection.py
Django db introspection assumes only the postgresql public schema is used, which is problematic when dealing with constraints in migrations. This PR overrides all of [django's postgres introspection](https://github.com/django/django/blob/master/django/db/backends/postgresql/introspection.py) methods so that they only lookup objects that belong to the current schema.
Example scenario, which this PR addresses:
Somewhere between django 1.5 and 1.8 the unique constraint naming convention was changed from `{app}_tmp{model}_{field}_key` to `{app}_{model}_{field}_{hash}_uniq`. 
1. Let's say we have a model with a unique field, which was created by django 1.5
2. Create a migration which removes the unique constraint
3. Run that migration for a single tenant
4. Run the backwards migration, which …
=> Fix: missing schema-aware introspection methods

tenant_schemas/management/commands/migrate_schemas.py, tenant_schemas/middleware.py
this commit fixes two issues impacting compatibility with django 1.10
* The migrate_schemas issue identified here: https://github.com/bernardopires/django-tenant-schemas/pull/371
* compatibility with Django's new style of middleware: https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware
=> fix compatibility issues with Django 1.10

tenant_schemas/routers.py
Hello, in case you run multiple databases (with only one as a tenant) the `TenantSyncRouter` does not work well. Please see the pull request diff, it's quite self-explanatory.
Cheers! M.
=> router multidb fix

tenant_schemas/middleware.py
There are some clients/libraries that won't call `.lower()` themselves on the url (unlike a standard web browser), so this should probably be done just to hedge against those cases. 
LMK if you have any questions!
=> Make sure hostname is always lowered before match

tenant_schemas/postgresql_backend/introspection.py
The query used to retrieve constraints issue a full scan (against all schemas), which is a really bad idea...
=> Fix query performance (avoid full scan).

docs/use.rst
I was following the documentation and since I never used `--username` with `createsuperuser` before, I entered my username by wrapping it in single quotes. It wasted an hour of my time and I was pulling my hair because I was unable to login no matter how many accounts I created.
I later realized that the single quotes were actually treated as part of the username instead of it treated like a string. I mean my username was literally `'admin'` and not `admin`.
=> Removed quotes from username value for createsuperuser command

README.rst, docs/index.rst, docs/use.rst, setup.py
Across the three versions of Django that django-tenant-schemas tries to support, there are three minimum versions of PostgreSQL.
- [Django 1.8](https://docs.djangoproject.com/en/1.8/ref/databases/#postgresql-notes) ~= PostgreSQL 9.0
- [Django 1.9](https://docs.djangoproject.com/en/1.9/ref/databases/#postgresql-notes) ~= PostgreSQL 9.1
- [Django 1.10](https://docs.djangoproject.com/en/1.10/ref/databases/#postgresql-notes) ~= PostgreSQL 9.2
Running the tests against PostgreSQL version 9.1 returns the following error (for each permutation in the tox environment list)
ERROR:  invalid value for parameter "search_path": "test, public"
DETAIL:  schema "test" does not exist
STATEMENT:  SET search_path = test,public
ERROR:  invalid value for parameter "search_path": "tenant1, public"
DETAIL: …
=> Document a position on supported versions of Django & PostgreSQL

docs/install.rst, tenant_schemas/apps.py, tenant_schemas/tests/test_apps.py
This fixes issue #430, where if people would like to override tenant_schemas commands then can do so with their own apps. Right now tenant_schemas won't work if any other app is placed before it. This change takes care of that.
=> #430 - Check wether tenant_schemas comes before any django apps instead of before all apps.

docs/install.rst
WARNINGS:
django.conf.settings: You should put 'tenant_schemas' before any django core applications in INSTALLED_APPS.
HINT: This is necessary to overwrite built-in django management commands with their schema-aware implementations.
=> Checker warns about 'tenant_schemas' position in INSTALLED_APPS

.travis.yml, dts_test_project/dts_test_project/settings.py, tenant_schemas/postgresql_backend/base.py, tenant_schemas/postgresql_backend/introspection.py, tenant_schemas/test/cases.py, tenant_schemas/tests/testcases.py, tox.ini
Tested with 1.11rc1 and 1.10 (Python 3.6).
I don't now if the Travis rule is able to select RC1 or if it follows the pip convention (so to replace by 1.11rc1 in waiting for stable release).
The change DatabaseWrapper._cursor() -> .cursor() will now generate server side cursors in Django 1.11 for iterator(). Cf django/django#7587
Our unit tests are slightly slower (about 8%) with Django 1.11 (6.30s) than Django 1.10 (5.84s) but I don't know why.
Note: benchmarks are just best of 5 runs on my computer, unit tests doesn't represent real cases....
=> Django 1.11 support

docs/advanced_usage.rst, docs/conf.py, docs/index.rst, docs/install.rst, tenant_schemas/middleware.py
In some situations, it might be useful to offer alternative tenant selection strategies. This PR intends to help with that.
For example, consider a website with a fixed URL, but with the `django-tenant-schemas` app. An approach for this website might be to pass the tenant through a special header, or to determine it in some other manner based on the request (e.g. using an OAuth token mapped to a tenant).
To make implementing these strategies simpler, this PR slightly modifies the current middlewares so that they all extend a `BaseTenantMiddleware`. In order to implement your own middleware, all you have to do is subclass `BaseTenantMiddleware` and implement your own version of the `get_tenant` method. This method returns the tenant (instance of `TENANT_MODEL`) based on the current …
=> Add BaseTenantMiddleware for easier custom middleware support

tenant_schemas/apps.py, tenant_schemas/tests/test_apps.py
No functionality change. Simply a verbosity enhancement to the current system checks to tag checks with IDs as Django intended. This way check IDs can be used to suppress warnings/errors when they are not relevant.
=> Add IDs to system checks. IDs can now be used in SILENCED_SYSTEM_CHECKS

tenant_schemas/middleware.py, tenant_schemas/postgresql_backend/base.py
Right now the ContentType cache is only cleared at the beginning of a request via the call from the middleware. However, anything that uses "with schema_context" or calls set_tenant() or set_schema() should also force a ContentType clear_cache() call. By moving it down to the database wrapper it will always happen on a schema change. Because set_tenant() is called in the middleware, it will also still happen at the same time it was called before (beginning of a request).
=> Fix ContentType clear_cache() to always happen at a schema change

dts_test_project/dts_test_app/migrations/0003_test_add_db_index.py, dts_test_project/dts_test_app/migrations/0004_test_alter_unique.py, tenant_schemas/postgresql_backend/introspection.py
There has been several fixes in Postgres introspection recently :
- https://github.com/django/django/commit/566726ff964b004f2a6adecc1e51197bc34d78d2#diff-7f14932a08ce1dbba14da7433e47f9fc
- https://github.com/django/django/commit/e585c43be91fb3e5005ddb4191f64142c62a2ec3#diff-7f14932a08ce1dbba14da7433e47f9fc
- https://github.com/django/django/commit/2f6cdc09c4db46ad13ff736b93a975bcd587abf4#diff-7f14932a08ce1dbba14da7433e47f9fc
(see [commits](https://github.com/django/django/commits/stable/1.11.x/django/db/backends/postgresql/introspection.py) and [file](https://github.com/django/django/blob/stable/1.11.x/django/db/backends/postgresql/introspection.py), and [django issue](https://code.djangoproject.com/ticket/26034))
The diff here is thus a copy-paste of django queries, plus some minor …
=> backported django postgres backend fixes

docs/use.rst
I am adding the `post_schema_sync` signal documentation which was missing. Right now the sender is `TenantMixin`. Although I believe it's better to make the Tenant Model itself as the sender, if that is possible. Your thoughts?
=> Add missing `post_schema_sync` signal documentation

tenant_schemas/management/commands/__init__.py, tenant_schemas/postgresql_backend/introspection.py, tenant_schemas/signals.py, tenant_schemas/test/client.py, tenant_schemas/tests/test_routes.py
* Fixed Django 4 syntax errors
* Fixed TypeError: \_\_init\_\_() missing 1 required positional argument: `get_response` (`TenantMiddleware`'s \_\_init\_\_())
* Fixed KeyError `schema_name` (`BaseTenantCommand`, in handle() function, the `schema_name` and `skip_public` were being removed from options. Removed this logic.)
=> Django 4 upgrade

.travis.yml, tenant_schemas/postgresql_backend/introspection.py
Support Django 4.0 by replacing the deprecated force_text with force_str
Fixes issue #675
=> Support Django 4.0 by replacing the deprecated force_text with force_str

docs/use.rst
There is a small typo in docs/use.rst.
Should read `similar` rather than `similiar`.
=> docs: Fix simple typo, similiar -> similar

.github/workflows/ci.yml, README.rst, docs/install.rst, pyproject.toml, src/tenant_schemas/postgresql_backend/base.py, tox.ini
- Remove `psycopg2-binary` as required dependency
- Add optional dependency groups for `[psycopg2]` and `[psycopg]`
- Update backend to support both PostgreSQL clients with fallback logic
- Expand CI matrix to test both psycopg2 and psycopg across all environments
- Update tox configuration with PostgreSQL client dimensions
- Add installation documentation for choosing PostgreSQL client
- Maintain backward compatibility while enabling psycopg3 adoption
=> Support both `psycopg2` and `psycopg` PostgreSQL clients

docs/conf.py, docs/install.rst, examples/tenant_tutorial/customers/views.py, examples/tenant_tutorial/tenant_tutorial/views.py, src/tenant_schemas/management/commands/__init__.py, src/tenant_schemas/management/commands/migrate.py, src/tenant_schemas/management/commands/migrate_schemas.py, src/tenant_schemas/models.py, src/tenant_schemas/postgresql_backend/base.py, src/tenant_schemas/postgresql_backend/introspection.py, src/tenant_schemas/routers.py, src/tenant_schemas/template_loaders.py, src/tenant_schemas/templatetags/tenant.py, src/tenant_schemas/test/client.py, src/tenant_schemas/tests/test_routes.py, src/tenant_schemas/tests/test_tenants.py, src/tenant_schemas/tests/test_utils.py, src/tenant_schemas/tests/testcases.py, src/tenant_schemas/utils.py
Modernize the codebase by removing compatibility code for old Django and Python versions, targeting Django 4.2+ and Python 3.8+ as per the project's compatibility guarantees.
- **30 `super()` calls modernized** across **14 files**
- Changed `super(ClassName, self).method_name(...)` → `super().method_name(...)`
- No functional changes, only syntax modernization
- Remove `try/except ImportError` for `django.apps` (always available in Django 4.2+)
- Remove `try/except ImportError` for `django.db.models.indexes.Index` (always available in Django 4.2+)
- Remove `try/except ImportError` for `StringIO` (Python 3.8+ always uses `io.StringIO`)
- Remove `allow_syncdb` method (Django 4.2+ only uses `allow_migrate`)
- Remove Django < 1.7 model compatibility code in router
- Remove `from __future__` …
=> Remove code for old Django and Python versions

dts_test_project/dts_test_app/migrations/0003_test_add_db_index.py, dts_test_project/dts_test_app/migrations/0004_test_alter_unique.py, src/tenant_schemas/apps.py, src/tenant_schemas/postgresql_backend/base.py, src/tenant_schemas/tests/test_apps.py, src/tenant_schemas/tests/test_psycopg3_recursion.py, src/tenant_schemas/tests/test_routes.py, src/tenant_schemas/tests/test_tenants.py, src/tenant_schemas/tests/testcases.py
Fixes RecursionError that occurs when using psycopg3 driver with DEBUG=True. The bug was caused by Django's SQL debug logging triggering psycopg3's mogrify operation, which opens fresh cursors that re-enter our `_cursor()` method, causing infinite recursion during search_path setting.
- **ContextVar Guard**: Prevents recursion during search_path operations
- **Parameterized Queries**: Uses `set_config()` with parameters instead of raw SQL formatting
- **Smart Caching**: Only sets search_path when tenant configuration actually changes  
- **Mogrify Optimization**: Skips unnecessary mogrify calls for parameterless queries
- **Isolated Unit Tests**: Mock-based tests safe for parallel execution without DB operations
- **Single Integration Test**: Real database test with proper cleanup for …
=> Fix `RecursionError` with `psycopg` when `DEBUG=True`
