- docs/use.rst
Added some sample code showing what I think is the intended way of wrapping an existing command using BaseTenantCommand.
> Add example usage of BaseTenantCommand

- docs/install.rst
- tenant_schemas/cache.py
- tenant_schemas/tests/__init__.py
- tenant_schemas/tests/test_cache.py
After facing a few issues with caching and reading the comments in #73, I've added two helper functions which can be used in the KEY_FUNCTION and REVERSE_KEY_FUNCTION cache settings.
> Cache key helper functions

- tenant_schemas/postgresql_backend/base.py
Addresses https://github.com/bernardopires/django-tenant-schemas/issues/312
@philfriesen FYI
> must set search_path again after a transaction rollback

- tenant_schemas/template_loaders.py
Fix regression introduced in cb8862d
- path construction changed from domain_url to schema_name
> Fixes #360

- tenant_schemas/management/commands/__init__.py
A simple implementation class was not bringing the options through:
class Command(BaseTenantCommand):
COMMAND_NAME = 'collectstatic'
Once this patch is applied, the expected output and behaviour is exhibited.
> Fix BaseTenantCommand to correctly add arguments from COMMAND_NAME

- docs/use.rst
> Wrote some docs for utils

- docs/use.rst
- dts_test_project/dts_test_project/settings.py
- tenant_schemas/log.py
- tenant_schemas/tests/__init__.py
- tenant_schemas/tests/test_log.py
- tenant_schemas/utils.py
- tox.ini
Based on example given by @regolith in #248 I've rolled it up into this pull request which can save the rest of us some boilerplate in our projects.
> Add TenantContextFilter for schema/domain logging

- tenant_schemas/models.py
- tenant_schemas/postgresql_backend/introspection.py
- tenant_schemas/utils.py
- Added introspection support for UUIDField.
- Added index order introspection.
- Added index type introspection.
- Allowed introspection to work regardless of table owner.
- Added introspection for expression-based index.
- Fix performance issue when querying constraint_column_usage.
> Add UUIDField, some index introspections and fix migrations performance issue

- tenant_schemas/models.py
- tenant_schemas/postgresql_backend/introspection.py
Reverts bernardopires/django-tenant-schemas#385
> Revert "Add UUIDField, some index introspections and fix migrations performance issue"

- tenant_schemas/models.py
- tenant_schemas/postgresql_backend/introspection.py
Reverts bernardopires/django-tenant-schemas#388
> Revert "Revert "Add UUIDField, some index introspections and fix migrations performance issue""

- docs/index.rst
- docs/utils.rst
> Documenting 'utils' module

- docs/test.rst
- tenant_schemas/test/cases.py
> Adding FastTenantTestCase and it's documentation

- tenant_schemas/management/commands/__init__.py
I had the same problem another commenter did, needed to fix this locally to create a superuser
> fixed error causing createsuperuser to fail for later versions of django

- .travis.yml
- dts_test_project/dts_test_project/settings.py
- tox.ini
If merging after #403 be sure to add 3.5 to the list of python versions in `.travis.yml` file.
> Add travis-ci.org integration

- tenant_schemas/postgresql_backend/introspection.py
Based on https://github.com/django/django/pull/7398
Fixes #405
> Updated indexes ordering introspection for PostgreSQL 9.6

- docs/install.rst
- tenant_schemas/middleware.py
- tenant_schemas/tests/test_routes.py
Hi @goodtune,
I've added upon @UnrealAkama 's PR and completed it with Tests and documentation.
Your review would be appreciated :)
> Added tests and documentation to PR #416

- tenant_schemas/models.py
- tenant_schemas/test/cases.py
- tenant_schemas/tests/testcases.py
> #424: Added IF EXISTS to DROP SCHEMA queries

- README.rst
> Update README to remove non-ASCII characters

- docs/conf.py
- docs/use.rst
- dts_test_project/dts_test_project/settings.py
- tenant_schemas/apps.py
- tenant_schemas/management/commands/collectstatic_schemas.py
- tenant_schemas/storage.py
- tox.ini
Re-opening #333 after rebasing on master and including documentation.
Resolves #182 and #291.
> TenantStorageMixin

- tenant_schemas/models.py
- tenant_schemas/tests/test_tenants.py
Make sure tenant delete() method is called, even when using django querysets bulk delete method.
> Fix for issue #446

- examples/tenant_tutorial/tenant_tutorial/settings.py
Update tenant_tutorial to Django 1.11
To create a PR
> Compatibility with Django 1.11 LTS (Tutorial) #477

- docs/install.rst
I made some improvements to the documentation that should make it a bit more clear on how to work with tenants and create them. 
Source of inspiration was issue #343
> Improved documentation on working with and creating tenants

- setup.py
Credits to @asottile who find this problem
> Ensure all packages are included
